### ISSUE TITLE
Latest "stable" being reported as 8.0.0.b32245, not 8.0.2.b37747?

### ISSUE THREAD

**Issue by justinclift** [getredash/setup#11]
Just noticed the `LATEST_VERSION` being reported for the 8.x series release is `8.0.0.b32245`:

https://github.com/getredash/setup/blob/cb47626b6823cbafac407b3e8991e97f53121f6e/setup.sh#L58

However, `8.0.2.b37747` is available.

Is the 8.0.2 build not considered stable, or is this just a case of something needing updating? :smile:

**Comment by wayne2000** [comment]
no matter what it is. seems always "404: Not Found"
https://raw.githubusercontent.com/getredash/setup/8.0.0.b32245/data/docker-compose.yml

**Comment by justinclift** [comment]
Closing this, as the LATEST_VERSION needs fixing anyway. :smile:
