### ISSUE TITLE
Repository 'http://archive.ubuntukylin.com/ukui focal InRelease

### ISSUE THREAD

**Issue by benxiaohair** [getredash/setup#15]
E: Repository 'http://archive.ubuntukylin.com/ukui focal InRelease' changed its 'Origin' value from 'LP-PPA-ubuntukylin-members-ukui3.0' to 'LP-PPA-ubuntukylin-members-ukui'
E: Repository 'http://archive.ubuntukylin.com/ukui focal InRelease' changed its 'Label' value from 'UKUI 3.0' to 'UKUI'

**Comment by justinclift** [comment]
Closing this as it doesn't seem to be relevant to the current state of our setup scripting. :wink:
