### ISSUE TITLE
I got an error when i run setup.sh

### ISSUE THREAD

**Issue by WatchLucky** [getredash/setup#17]
setup.sh stop and throw an error at
" wget https://raw.githubusercontent.com/getredash/setup/${GIT_BRANCH}/data/docker-compose.yml
"
connect refuse 

 i want to  download it manually , but i can find it .

**Comment by Lyrwon** [comment]
Hi,

replace ${GIT_BRANCH} wit master and it will work

wget https://raw.githubusercontent.com/getredash/setup/${GIT_BRANCH}/data/docker-compose.yml
wget https://raw.githubusercontent.com/getredash/setup/master/data/docker-compose.yml

**Comment by justinclift** [comment]
Closing this as it seems related to an outdated version of our setup scripting. :wink:
