### ISSUE TITLE
Upgrade Postgres version as Postgres 9.6 is becoming EOL on Nov 11, 2021

### ISSUE THREAD

**Issue by albrycht** [getredash/setup#24]
Hi,
I've been installing Redash for my clients alongside some custom software. Few of them had been raising an issue of Postgres 9.6 reaching End Of Life status soon.
Do you plan to upgrade Postgres to a newer one?

**Comment by snickerjp** [comment]
@albrycht #55 PostgreSQL updated.😄

**Comment by justinclift** [comment]
Closing this as PostgreSQL was updated a while ago. :smile:
