### ISSUE TITLE
Add documentation about fixing docker-compose after removing redash

### ISSUE THREAD

**Issue by johnbullnz** [getredash/setup#27]
After removing redash from a server any use of docker-compose yields the following error:

```
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/opt/redash/docker-compose.yml'
```

This effectively makes docker-compose unusable for any other purpose. The cause is these two lines in the user's  `.profile` file which are added by the setup script.

```
export COMPOSE_PROJECT_NAME=redash
export COMPOSE_FILE=/opt/redash/docker-compose.yml
```

It would be useful if this were documented in the README.

**Comment by verbeckii** [comment]
I just faced with this issue

So how I can fix it?
I can't start any other dockers due to redash script just hardcoded path for docekr-compose.yml...

**Comment by verbeckii** [comment]
I no longer have /opt/redash but it still create every time redash_network when I'm creating a new others docker-compose
How can I totally remove redash_network?

**Comment by PhilippeAccorsi** [comment]
I discover the same problem today.
I have remove two line in `.profile` but same problem. If i try `docker compose --version` i have error: `stat /opt/redash/docker-compose.yml: no such file or directory`.

What is the solution to solved that shitty installation ? Why redash add some config in `.profile` ? We use docker to not have this kind of config lost in system.

**Comment by FnxMcNoob** [comment]
@PhilippeAccorsi I accidentally ran into and fixed this today also.

I have this running via WSL so for me, so after running the steps in #28 I also ran `wsl --shutdown` which restarted both my Ubuntu and Docker instances. My assumption is that from the same terminal, you just need to source `.profile` again. e.g.  `. ~/.profile`

If that isn't the full solution, restart docker.

**Comment by moninformateur** [comment]
What a shit software holy hell.

**Comment by dev2o** [comment]
Odd enough, after many tries of grep looking for the configuration causing this issue,  I ran ``` source ~/.profile ``` and then ``` nano ~/.profile ```, and sure enough, the config was in there.
