### ISSUE TITLE
Support for version 10

### ISSUE THREAD

**Issue by frafra** [getredash/setup#30]
It would be nice to have this repository updated for Redash v10.

**Comment by justinclift** [comment]
One option is to use the setup.sh from the newdash fork:

&nbsp; &nbsp; https://github.com/getnewdash/setup

That uses the 10.0.0-beta.b49597 docker image by default.

On Ubuntu 20.04 LTS you can just run this:

```
$ curl https://raw.githubusercontent.com/getnewdash/setup/master/setup.sh | bash
```

If you want to review the script before running it instead, then do this:

```
$ curl -O https://raw.githubusercontent.com/getnewdash/setup/master/setup.sh
$ chmod +x setup.sh
$ ./setup.sh
```

**Comment by ckljohn** [comment]
Need to update this part.
https://github.com/getredash/setup/blob/cb47626b6823cbafac407b3e8991e97f53121f6e/data/docker-compose.yml#L27

ref:
https://github.com/getredash/redash/blob/master/CHANGELOG.md#upgrading

**Comment by justinclift** [comment]
Doesn't seem like it?

Saying that because those two queues are already in this getredash/setup repository:

https://github.com/getredash/setup/blob/5dbd05fab945187af6c1808a4331aae1fc931486/data/docker-compose.yml#L27

The piece in the CHANGELOG.md#upgrading, adds three new queues to those, handled by a new worker container: `periodic emails default`.

**Comment by prognostikos** [comment]
We used the newdash version of the script and all went well except that `/etc/cron.daily/renew-redash-cert` was created without execute permissions so I had to manually renew the cert using `/opt/redash/renew-cert.sh`. Noting it here in case anyone else runs into this (also as the newdash repo has issues turned off).

**Comment by justinclift** [comment]
Oh, that's a good tip @prognostikos.  I'll take a look at that perms problem this weekend. :smile:

The [newdash/setup](https://github.com/getnewdash/setup) repo has Issues turned on now too.  Completely didn't realise it wasn't enabled. :facepalm:

**Comment by justinclift** [comment]
@prognostikos That "renew-redash-cert" script... I'm not seeing it anywhere when looking through the setup repo.

Am I being blind or just need more coffee or something? :smile:

**Comment by prognostikos** [comment]
@justinclift you're not blind, I can't find it either. I don't think it's related to the setup script. Sorry for the false alarm.

**Comment by justinclift** [comment]
Closing this as the setup scripting was significantly reworked yesterday to pull in Redash 10.x (and other things like supporting more Linux distributions).  

Of course, it'll need updating again when the next release is ready.
