### ISSUE TITLE
LDAP missing requirements

### ISSUE THREAD

**Issue by damajor** [getredash/setup#34]
Please include LDAP3 libs in the container builds.

Scheduler container keeps crashing with:
`The ldap3 library was not found. This is required to use LDAP authentication (see requirements.txt).`

**Comment by justinclift** [comment]
Hmmm, I'm not really sure what to do with this.  It seems like a mis-filed issue that should be on the main Redash repository instead.

That being said, I'm not sure if `Please include LDAP3 libs in the container builds` is requesting the Python `ldap3` library, or perhaps requesting an OS level ldap3 library?

* The Python `ldap3` library [seems to be included these days](https://github.com/getredash/redash/blob/1672cd92801b2555b6a95a1c95e7b3328f0664d0/poetry.lock#L2073-L2082)
* The OS level ldap3 library [seems to have a licensing issue of some sort](https://github.com/getredash/redash/blob/1672cd92801b2555b6a95a1c95e7b3328f0664d0/Dockerfile#L92-L93)

@damajor Is this still issue relevant to you?

**Comment by damajor** [comment]
Not relevant anymore, I am not able to test it at this moment.

**Comment by justinclift** [comment]
No worries at all @damajor.  Thanks for taking the time to file the issue when it came up for you. :smile:
