### ISSUE TITLE
Ubuntu 18.04 has reached EOL

### ISSUE THREAD

**Issue by justinclift** [getredash/setup#43]
Ubuntu 18.04 reached its official End Of Life (EOL) in April for the majority of users (aka those without support contracts):

https://ubuntu.com/about/release-cycle

So, we need to update this for a newer base server version.  Probably Ubuntu 20.04, as that's likely the easiest approach that'll do the job.

**Comment by mike-ua** [comment]
...but 22.04 will be less work later ;-)

or maybe even a rolling release to forget updates forever?
I switched to Solus/Budgie 6 years ago and am still waiting for it to crash so I can finally clean and reinstall :))))
Stream? Tumbleweed? Rawhide?

Just a thought, no response necessary.

**Comment by justinclift** [comment]
> ...but 22.04 will be less work later ;-)

While that probably seems like it's true at first thought, our (recently written) development docs on the wiki are all based upon 20.04 (LTS).

So the "known good" base is likely that, with variation from that likely to actually create extra effort for no real benefit. :wink:

**Comment by snickerjp** [comment]
@mike-ua 
> ...but 22.04 will be less work later ;-)

With the #44 change, it also works on Ubuntu 22.04.

```bash
$ cat /etc/issue
Ubuntu 22.04.3 LTS \n \l

$ sudo docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED         STATUS         PORTS                                        NAMES
7bd592094933   redash/nginx:latest          "nginx -g 'daemon of…"   3 minutes ago   Up 3 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 443/tcp   redash-nginx-1
aabfed0f1fd8   redash/redash:8.0.0.b32245   "/app/bin/docker-ent…"   3 minutes ago   Up 3 minutes   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp    redash-server-1
75095e362415   redash/redash:8.0.0.b32245   "/app/bin/docker-ent…"   3 minutes ago   Up 3 minutes   5000/tcp                                     redash-scheduled_worker-1
dc9d2e74423e   redash/redash:8.0.0.b32245   "/app/bin/docker-ent…"   3 minutes ago   Up 3 minutes   5000/tcp                                     redash-adhoc_worker-1
c477950d9b13   redash/redash:8.0.0.b32245   "/app/bin/docker-ent…"   3 minutes ago   Up 3 minutes   5000/tcp                                     redash-scheduler-1
7709c108146c   postgres:9.6-alpine          "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes   5432/tcp                                     redash-postgres-1
857397da5035   redis:5.0-alpine             "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes   6379/tcp                                     redash-redis-1
```
![image](https://github.com/getredash/setup/assets/1247622/0cc6f2e0-565a-472f-ae16-c653620cc149)

**Comment by mike-ua** [comment]
@snickerjp excellent news! After putting aside attempts to install Redash for a while (focusing on Streamlit), I revisited a few weeks ago (this time with help from ChatGPT), but still no luck.  I even tried on a RaspberryPi4 (4GB) on 20.04, but there I've also been stopped by the wi-fi.  I give it another go over the weekend.

**Comment by justinclift** [comment]
As a data point, I've been re-working the setup.sh script in this PR https://github.com/getredash/setup/pull/58.

That adds support for Debian 12, and I'll probably add RHEL and SLES too.

**Comment by justinclift** [comment]
Closing this as we've updated the OS support for newer Ubuntu.  And also added support for other Linux distro's as well (Debian, RHEL and compatible, etc). :smile:
