### ISSUE TITLE
Setup completely breaks docker

### ISSUE THREAD

**Issue by nexovec** [getredash/setup#48]
After `./setup.sh` and `docker compose up`, every call to `docker compose up` from anywhere results in something like this:

```bash
not@important:~/streamlit-workshop$ docker compose up
[+] Running 7/0
 ✔ Container redash-postgres-1          Running                                                                                                                                            0.0s 
 ✔ Container redash-redis-1             Running                                                                                                                                            0.0s 
 ✔ Container redash-adhoc_worker-1      Running                                                                                                                                            0.0s 
 ✔ Container redash-scheduler-1         Running                                                                                                                                            0.0s 
 ✔ Container redash-scheduled_worker-1  Running                                                                                                                                            0.0s 
 ✔ Container redash-server-1            Running                                                                                                                                            0.0s 
 ✔ Container redash-nginx-1             Running                                                                                                                                            0.0s 
Attaching to redash-adhoc_worker-1, redash-nginx-1, redash-postgres-1, redash-redis-1, redash-scheduled_worker-1, redash-scheduler-1, redash-server-1
redash-scheduler-1         | [2023-12-05 22:33:14,501][PID:24][INFO][Beat] Scheduler: Sending due task sync_user_details (redash.tasks.sync_user_details)
redash-scheduler-1         | [2023-12-05 22:33:14,504][PID:1][INFO][MainProcess] Received task: redash.tasks.sync_user_details[5a16ec2e-2195-464a-bd17-8cab90ca9ad7]   expires:[2023-12-05 22:33:59.502083+00:00]
redash-scheduler-1         | [2023-12-05 22:33:14,506][PID:585][INFO][ForkPoolWorker-563] Task redash.tasks.sync_user_details[5a16ec2e-2195-464a-bd17-8cab90ca9ad7] succeeded in 0.000744658056647s: None
redash-scheduler-1         | [2023-12-05 22:33:22,970][PID:24][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
redash-scheduler-1         | [2023-12-05 22:33:22,973][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[d42edeb4-c232-4e6f-b39d-aa6649523fcc]  
redash-scheduler-1         | [2023-12-05 22:33:22,975][PID:585][INFO][ForkPoolWorker-563] task_name=redash.tasks.refresh_queries task_id=d42edeb4-c232-4e6f-b39d-aa6649523fcc Refreshing queries...
redash-scheduler-1         | [2023-12-05 22:33:22,983][PID:585][INFO][ForkPoolWorker-563] task_name=redash.tasks.refresh_queries task_id=d42edeb4-c232-4e6f-b39d-aa6649523fcc Done refreshing queries. Found 0 outdated queries: []
redash-scheduler-1         | [2023-12-05 22:33:22,986][PID:585][INFO][ForkPoolWorker-563] Task redash.tasks.refresh_queries[d42edeb4-c232-4e6f-b39d-aa6649523fcc] succeeded in 0.0114565880504s: None
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 7/7
 ✔ Container redash-adhoc_worker-1      Stopped                                                                                                                                            3.1s 
 ✔ Container redash-nginx-1             Stopped                                                                                                                                            1.0s 
 ✔ Container redash-scheduler-1         Stopped                                                                                                                                            3.5s 
 ✔ Container redash-scheduled_worker-1  Stopped                                                                                                                                            3.8s 
 ✔ Container redash-server-1            Stopped                                                                                                                                            1.5s 
 ✔ Container redash-postgres-1          Stopped                                                                                                                                            1.4s 
 ✔ Container redash-redis-1             Stopped                                                                                                                                            1.1s 
canceled
```

This project is not redash. Reinstalling docker with

```bash
sudo systemctl stop docker
sudo apt-get purge ...
sudo rm -rf /etc/docker /var/lib/docker
...
```

didn't help. I'll have to reinstall the OS on multiple servers and on my personal PC. This is completely terrible and I might get fired. Even so I hope it's just my fault. 

Issue was tested on Debian GNU/Linux 12 (bookworm) x86_64 docker version 20.10.24+dfsg1 and Pop!_OS 22.04 LTS x86_64 docker version 24.0.7. Compose upping was tested on multiple different repositories, with a similar result.

**Comment by justinclift** [comment]
> This project is not redash.

???

> This is completely terrible and I might get fired.

Oh come on.  Installing brand new software you're unfamiliar with on *production* isn't generally a good move.

Most people would try things in a test environment of some sort first to gain familiarity... :angry:

**Comment by nexovec** [comment]
It isn't prod, but it's still a hassle. I generally expect things to not break my system, that's why we're using docker in the first place. I do not know how to respond to the text "???"

**Comment by justinclift** [comment]
It's still unclear what's broken.  You've just said "This project is not redash" and not giving any other details about what's going wrong.

**Comment by nexovec** [comment]
The issue is that when I do `docker compose up` in any project, it tries to up redash.

**Comment by justinclift** [comment]
Ahhh.  That'll probably be from these two lines then:

https://github.com/getredash/setup/blob/e611a6af966124eb974d1d953f64a10c5e9767e6/setup.sh#L70-L71

Those lines make Redash the default docker project.  It's useful for most people, but can be unwanted in situations where people run multiple docker things.

To fix it, just comment out those two lines it adds to the end of `.profile` (its a text file) in the user home directory.

**Comment by justinclift** [comment]
Oh, you'll probably need to restart your login session after editing that file as it's only read when you log in.

**Comment by nexovec** [comment]
I did reboot. also I found the cause of the issue.

There's

```bash
  echo "export COMPOSE_PROJECT_NAME=redash" >>~/.profile
  echo "export COMPOSE_FILE=$REDASH_BASE_PATH/docker-compose.yml" >>~/.profile
```

in the install script. You wrote that. What were you thinking?
I don't like that docker prefers the variables to the CLI arguments, but it seems to be the case, should I also open an issue for this in docker do you think?

**Comment by justinclift** [comment]
> You wrote that. What were you thinking?

Are you kidding?

That's the second time in this same issue you're giving crappy attitude to people volunteering their free time.

I understand you're young and probably stressed, but please... do better. :smile:

**Comment by nexovec** [comment]
> Oh come on. Installing brand new software you're unfamiliar with on _production_ isn't generally a good move.

It's relevant to the discussion that it's openly encouraged in the README that it can be used in production.

**Comment by justinclift** [comment]
Yep, this script has been used by many people to set up their production Redash instances. :smile:

It definitely needs some updating though, as the project has been relaunched as being Community Led and there are newer versions of Ubuntu LTS (etc) out.

**Comment by nexovec** [comment]
> > You wrote that. What were you thinking?
> 
> Are you kidding?
> 
> That's the second time in this same issue you're giving crappy attitude to people volunteering their free time.
> 
> I understand you're young and probably stressed, but please... do better. 

It's great that you volunteer and I can totally relate, and it's not my intention to be hostile. But this still isn't very good.

**Comment by nexovec** [comment]
> Yep, this script has been used by many people to set up their production Redash instances. 😄

So all these people now have broken docker?

**Comment by justinclift** [comment]
No, they have Docker working perfectly fine ***for their Redash installation***, which is what they used the script for.

It seems like your setup is installing several Docker related things on the same server.  Clearly that means you need to do a bit of extra work (aka change the .profile).  It seems like you're getting bent out of shape by it, and I'm not sure why.

Anyway, I'm done arguing with you.

**Comment by nexovec** [comment]
Oh, okay.

So this is not considered a bug?

**Comment by justinclift** [comment]
No, it's just different use cases having different (directly conflicting) requirements.

There could indeed be a better approach that works for everyone.  No-one (so far) has been able to think of how to make it work though.

**Comment by nexovec** [comment]
Here's the modified function in the setup script that works for me:

```
setup_compose() {
  REQUESTED_CHANNEL=stable
  LATEST_VERSION=$(curl -s "https://version.redash.io/api/releases?channel=$REQUESTED_CHANNEL" | json_pp | grep "docker_image" | head -n 1 | awk 'BEGIN{FS=":"}{print $3}' | awk 'BEGIN{FS="\""}{print $1}')

  cd "$REDASH_BASE_PATH"
  GIT_BRANCH="${REDASH_BRANCH:-master}" # Default branch/version to master if not specified in REDASH_BRANCH env var
  curl -OL https://raw.githubusercontent.com/getredash/setup/"$GIT_BRANCH"/data/docker-compose.yml
  sed -ri "s/image: redash\/redash:([A-Za-z0-9.-]*)/image: redash\/redash:$LATEST_VERSION/" docker-compose.yml
  # echo "export COMPOSE_PROJECT_NAME=redash" >>~/.profile
  # echo "export COMPOSE_FILE=$REDASH_BASE_PATH/docker-compose.yml" >>~/.profile
  export COMPOSE_PROJECT_NAME=redash
  export COMPOSE_FILE="$REDASH_BASE_PATH"/docker-compose.yml
  sudo docker-compose run --rm server create_db
  sudo docker-compose -f $COMPOSE_FILE --project-name $COMPOSE_PROJECT_NAME up -d --build --force-recreate
}
```

here is how you then remove redash completely in case something went wrong(with your current script you also have to remove from `~/.profile`):

```
docker-compose down --volumes --remove-orphans
sudo rm -rf /opt/redash/
sudo systemctl restart docker
```

you people have made a number of questionable decisions in the setup script, including curling the compose file, and how it writes a different postgres password into the env file each time you run. Don't be angry at me, I'm just trying to get redash to work.

**Comment by nexovec** [comment]
This solved the issue for me, I'm leaving this open, I'm assuming you'll want to verify and make the changes yourself. Consider making the uninstall script as well.

**Comment by justinclift** [comment]
> sudo systemctl restart docker

In theory, you shouldn't need to restart the docker daemon after doing that.

What's happening for you if you don't?

**Comment by nexovec** [comment]
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"` happens for me. You're correct that that is a little unexpected.

**Comment by justinclift** [comment]
Hmmm, that indicates some of the Redash docker containers are still running.  Rough guess, but perhaps your `docker-compose down` may need a bit of adjustment?

**Comment by nexovec** [comment]
option 1. There's a leftover container after `sudo docker-compose run --rm server create_db` in the setup.
option 2. There's some undeleted docker volumes. (this would be very surprising, because that's what the `--volumes` is for)

But does this really matter since after restart it's okay?

**Comment by justinclift** [comment]
> But does this really matter since after restart it's okay?

Probably not.  Just more a matter of "hmmm, I wonder why it did that...?". :grin:

**Comment by justinclift** [comment]
As a data point, I've reworked the setup.sh script today so it doesn't automatically set those environment variables. :smile:

Instead, there's a secondary script which can do it, and the setup script tells people to run that if they want to.  Like this:

```
...
 ✔ Container redash-scheduler-1         Started    5.7s 
 ✔ Container redash-scheduled_worker-1  Started    5.7s 
 ✔ Container redash-worker-1            Started    5.1s 
 ✔ Container redash-nginx-1             Started    4.6s 

Redash has been installed and is ready for configuring at http://YOUR_HOSTNAME:5000

If you want Redash to be your default Docker project when you login to this server
in future, then please run /opt/redash/redash_make_default.sh

That will set some Docker specific environment variables just for Redash.  If you
already use Docker compose on this computer for other things, you probably don't want that.
```

Then, if/when the user runs the mentioned 2nd script:

```
$ /opt/redash/redash_make_default.sh
Redash has now been set as the default Docker Compose project
```

**Comment by justinclift** [comment]
> it writes a different postgres password into the env file each time you run

When looking at the script today, that surprised me as well (I'm not the original author).

I've left that bit "as is" for now, but am seriously tempted to change that too.

Will think it over. :wink:

**Comment by justinclift** [comment]
> it writes a different postgres password into the env file each time you run

For now, I've left that piece alone.

That "nuke the env file on each run" behaviour does seem to catch people out pretty often though, so I'm thinking we'll probably change it in the near future.  Am just wanting to focus on other pieces first before I really think it through properly.

**Comment by justinclift** [comment]
Oh, that change to "no longer automatically add stuff to the users profile" has been merged now too.  So future people using the setup script shouldn't find their Docker Compose suddenly acting weirdly. :wink:

**Comment by justinclift** [comment]
> it writes a different postgres password into the env file each time you run

Opened a discussion about it here, if you're up for giving it some thought. :smile:

https://github.com/getredash/redash/discussions/6840

**Comment by justinclift** [comment]
> it writes a different postgres password into the env file each time you run

PR to stop that from happening: https://github.com/getredash/setup/pull/60

When (if) that gets merged, I think we can close this issue too. :smile:

**Comment by justinclift** [comment]
That PR has been merged, so I'll close this issue now.  Everything mentioned in this issue has been fixed. :smile:
