### ISSUE TITLE
Unable to find Zabbix Datasource

### ISSUE THREAD

**Issue by venkatashreevaatsava** [getredash/setup#49]
Hi Team,
I have recently setup redash instance using setup.sh and trying to integrate Zabbix with It.

I could not find Zabbix Datasource within datasources list

Can you help me

**Comment by masayuki038** [comment]
@venkatashreevaatsava It looks like there is no datasource for Zabbix in Redash...
https://github.com/getredash/redash/blob/master/README.md#supported-data-sources

**Comment by snickerjp** [comment]
@venkatashreevaatsava 

What backend database do you use for Zabbix?

Generally, I use MySQL, PostgreSQL, or Oracle.
In this case it is supported.

By
- MySQL data source
- PostgreSQL data source
- Oracle data source.

**Comment by justinclift** [comment]
Closing this as it doesn't seem like an issue with the Redash setup scripting. :wink:

If this problem is still happening and needs a solution though, please file an issue with the details on the main Redash repository:

https://github.com/getredash/redash/issues/new/choose
