### ISSUE TITLE
Is there any way to get this to run on Fedora Server OS?

### ISSUE THREAD

**Issue by danielrosehill** [getredash/setup#63]
I know it's specifically not listed as a supported OS but (I would have thought) it's somewhat close to RHEL so perhaps there's some hope.

If it's of any use, this is the terminal output I get when trying to run it:

![image](https://github.com/getredash/setup/assets/40233203/75024b7c-ace6-4086-b59f-e4b19dca0fab)

I'd happily pursue any directions that might get it to work and share the results ... I'm just not sure where to start trying!

**Comment by lucydodo** [comment]
https://github.com/getredash/setup/blob/1299b8fb3e68b19890e736785a9d1e6a76a3d13c/setup.sh#L279
By adding `fedora` to line 279 of the above script, script will be run commands used in RHEL on Fedora too.
> As an aside, I'm installing Fedora on my local VM right now to test that it works before pushing this change upstream.

**Comment by justinclift** [comment]
Yeah, it'll probably be super close to a RHEL installation and likely won't take much effort to get working. :smile:

**Comment by justinclift** [comment]
Thinking about it, what *might* cause issues is that the existing script uses the official Docker Community Edition repo and packages for ***CentOS***:

https://github.com/getredash/setup/blob/1299b8fb3e68b19890e736785a9d1e6a76a3d13c/setup.sh#L99

It looks like they have a Fedora specific repository and packages: https://download.docker.com/linux/

So the script will probably need to use those instead of grabbing the CentOS ones. :smile:

Should be an easy change to make.  In theory. :smile:

**Comment by danielrosehill** [comment]
Hey @lucydodo. Sorry for the duplicate. I thought for a moment that the installer was a third-party project (and you were two separate teams!). Will check out the updated script in the PR you opened and pass on validation if it's of any help!

**Comment by lucydodo** [comment]
Yes, it's a bit different, so I've modified it by referring to the official Docker documentation. and I just created a PR. :)

**Comment by lucydodo** [comment]
@danielrosehill No need to sorry, on the contrary, thanks for the wonderful suggestion.
The PR is currently pending review, but until it's merged, you can test it with the command below.
```bash
curl -O https://raw.githubusercontent.com/getredash/setup/fedora/setup.sh
chmod +x ./setup.sh
sudo ./setup.sh
```

**Comment by justinclift** [comment]
@lucydodo It's merged. :smile:

@danielrosehill If you grab the setup script again (with the merged updates), then it should work for you. :smile:

**Comment by justinclift** [comment]
As a data point I just tried the updated script (with @lucydodo's changes) on Fedora 38, 39, and 40 (beta).  x86_64 architecture, "minimal" install.

It installed Redash (preview, using `./setup --preview`) perfectly fine, with no errors at all. :smile:

Also updated the README file in the repo to add those extra Fedora versions to the "Tested" list. :smile:

**Comment by danielrosehill** [comment]
And ... we're up and running!

![redash](https://github.com/getredash/setup/assets/40233203/181b7c61-008a-4a2b-88ce-bf74188186c4)

Amazing! Thanks so much, @lucydodo and @justinclift .
(I may have mentioned earlier but just for the sake of validation: running on Fedora Server 39)

**Comment by lucydodo** [comment]
I'm glad to hear the issue has been resolved, and I'll close the issue. :)
