### ISSUE TITLE
Docker compose YAML link broken in setup docs

### ISSUE THREAD

**Issue by rdbell** [getredash/setup#66]
https://redash.io/help/open-source/setup#docker

```
<li>Download our recommended <a href="[https://github.com/getredash/setup/blob/master/data/docker-compose.yml](view-source:https://github.com/getredash/setup/blob/master/data/docker-compose.yml)" target="_blank" rel="nofollow noopener noreferrer">Docker Compose configuration</a> and create initial configuration.</li>
```

```
<p>To run Redash you need several instances of Redash (API server and background workers to run queries) along with Redis and PostgreSQL. If you don’t want or can’t use our images or <a href="[https://github.com/getredash/setup](view-source:https://github.com/getredash/setup)" target="_blank" rel="nofollow noopener noreferrer">Setup Script</a>, you can refer to the <a href="[https://github.com/getredash/setup/blob/master/data/docker-compose.yml](view-source:https://github.com/getredash/setup/blob/master/data/docker-compose.yml)" target="_blank" rel="nofollow noopener noreferrer">Docker Compose configuration</a> to understand what services you need to define.</p>
```

**Comment by justinclift** [comment]
Oh, good point.  I've been updating the build pieces of this setup script, but haven't really taken a step back and looked at things like that.

I'll take a look at it some time over the next few days.

Thanks for bringing it to our attention @rdbell. :smile:

**Comment by justinclift** [comment]
Ok, it's taking more than a few days.  It'll probably be this weekend sometime though, as I'm already doing some housekeeping for projects. :smile:

**Comment by lucydodo** [comment]
@justinclift Looking at the history, it was a minor issue with a file name chnage(`docker-compose.yml` to `compose.yaml`)
If you don't mind, can I fix it and create a PR?

**Comment by justinclift** [comment]
Definitely, go for it. :smile:

**Comment by lucydodo** [comment]
PR: https://github.com/getredash/website/pull/701
Cool, I've make a PR to patch with what @rdbell mentioned, as well as a couple other pieces of text that weren't edited.

**Comment by justinclift** [comment]
@rdbell The documentation has been updated to use the new `compose.yaml` name now, thanks to [the PR](https://github.com/getredash/website/pull/701) from @lucydodo. :smile:
