### ISSUE TITLE
Digital Ocean Marketplace link is broken in setup docs

### ISSUE THREAD

**Issue by rdbell** [getredash/setup#67]
```
<p>To get started on DigitalOcean, you can use the image from DigitalOcean’s Marketplace (<a href="[https://marketplace.digitalocean.com/apps/redash](view-source:https://marketplace.digitalocean.com/apps/redash)" target="_blank" rel="nofollow noopener noreferrer">Redash on the Marketplace</a>). Once started the Droplet, proceed to ”<a href="[#setup-redash-instance-setup](view-source:https://redash.io/help/open-source/setup/#setup-redash-instance-setup)">Setup</a>“.</p>
```

**Comment by justinclift** [comment]
Yeah, I *think* the Digital Ocean marketplace thing isn't there any more, but I've not personally looked.

**Comment by justinclift** [comment]
@lucydodo Any interest in looking at this text too?

**Comment by lucydodo** [comment]
Sure, but let's have dinner first and take a look. and I'll also look for other related issues. :)

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by lucydodo** [comment]
> https://github.com/getredash/redash/discussions/6812

Well, it looks like Redash has been removed from the Digital Ocean Marketplace. So should we delete it?

**Comment by justinclift** [comment]
Yeah, that's probably the right way to go. :smile:

**Comment by lucydodo** [comment]
Okay, I've created a PR.

**Comment by justinclift** [comment]
@rdbell The Digital Ocean bit has been removed from the website, thanks to @lucydodo. :smile:
