### ISSUE TITLE
Haw to load sqlite file from host system

### ISSUE THREAD

**Issue by LucaGabi** [getredash/setup#7]
Hi, 
Where to add the docker directive bellow to share host sqlite db with container ?
```
volumes:
      - /tmp/sqlite:/tmp/sqlite
```

**Comment by arikfr** [comment]
As you need it on all Redash containers add it to the `x-redash-service` definition, then run `docker-compose up -d`. 

If you need further help, please use the [forum](discuss.redash.io).
