### ISSUE TITLE
issue with install script

### ISSUE THREAD

**Issue by samuellhwarren** [getredash/setup#70]
./setup.sh: 279: PROFILE: parameter not set

**Comment by justinclift** [comment]
Hmmm, that's new.  Let me check quickly.

**Comment by justinclift** [comment]
Just tested the script in a new Debian 12 VM, and didn't get that error so it's not something affecting all situations.

---

Looking through the script a bit more closely, I can see one potential problem in it which might have caused that error for you.  Added a fix for it.

Would you be ok to [download the script](https://github.com/getredash/setup/raw/master/setup.sh) (ie get the likely fixed version) and try running it again? :smile:

**Comment by samuellhwarren** [comment]
works, thanks again!
