### ISSUE TITLE
sudo ./setup.sh startup - error sed: 1: "compose.yaml": command c expects \ followed by text

### ISSUE THREAD

**Issue by lehungio** [getredash/setup#73]
![Screen Shot 2024-08-31 at 13 17 10](https://github.com/user-attachments/assets/350e8215-c2fa-4807-932a-366cb7cf9acd)

```
sudo ./setup.sh startup           

Redash installation script. :)

Docker and Docker Compose are already installed, so skipping that step.
** Creating /opt/redash directory structure for Redash **
** Creating Redash environment file **

Environment file already exists, reusing that one + and adding any missing (mandatory) values

** Creating Redash Docker compose file **
sed: 1: "compose.yaml": command c expects \ followed by text
```

**Comment by lucydodo** [comment]
I just confirmed that it works fine on my system. (Ubuntu 24.04 via WSL2)
Can you please let me know what OS, shell version, etc. you are using to troubleshoot?

**Comment by justinclift** [comment]
@lehungio Also, any idea which shell you're using?  Just in case it's not bash.

@lucydodo At a guess, my suspicion is it's probably something to do with the:

```
Docker and Docker Compose are already installed, so skipping that step.
```

It probably means there's a code path it's going down that has a bug in it. :smile:

**Comment by justinclift** [comment]
Oops, I totally forgot about this.  I should have time to look into it over the next few days.

**Comment by justinclift** [comment]
@lehungio Looking into this now.  Which Operating System is this error occuring on?

Asking because I'm not hitting this error when trying things out just now, so I'll probably have to set up a VM with the same OS as you and see if that gets the problem to show up. :smile:

**Comment by lehungio** [comment]
@justinclift Thank you for the feedback. I was using macOS, but it seems the script is not supported on macOS. I switched to Ubuntu, and everything works as expected. 

![Screen Shot 2024-09-25 at 22 27 31](https://github.com/user-attachments/assets/4e15a426-24f8-40dd-af7e-931e02200d61)

Ref: https://github.com/lecaoquochung/docker-images/actions/runs/11033940803/job/30646296271#step:7:21

**Comment by justinclift** [comment]
Ahhhh yeah.  You're right, the script is more for setting up a production oriented Redash than a development oriented one.

For macOS, it's pretty much assumed that's going to be a development oriented thing, but... that might not be the best assumption. :wink:

Ubuntu though should be fine, so you should be all good with that. :smile:

**Comment by justinclift** [comment]
@lehungio Looking over the Linux run for your Redash setup there, it kind of looks like the setup script is being run twice:

https://github.com/lecaoquochung/docker-images/actions/runs/11033940803/job/30646317544#step:7:744

That won't really hurt anything, as modern releases of the setup script detect that situation and make sure to not go wrong.  But it might be something you want to optimise a bit by only running the script once.

Just thinking out loud anyway. :smile:
