### ISSUE TITLE
Why does your script modify my profile without prompting?

### ISSUE THREAD

**Issue by rwsv3** [getredash/setup#8]
This line should absolutely be removed
https://github.com/getredash/setup/blob/master/setup.sh#L64-L65

There is no reason to modify someone's bash profile without giving them a prompt or at least informing them that you are making changes. 

This set's the COMPOSE_* environment variables for every docker-compose command run thereafter. 
Please consider removing this line, you are already exporting the variables no need to lock the user in.

**Comment by arikfr** [comment]
Sorry about the unexpected surprise. 

This is only a reference script and meant to be used on a dedicated server, where usually there is no issue with updating the profile. When using it to setup on a machine used for other things, I sort of assume people will read the script and understand what it does / modify it to their needs.

Btw, the reason we export this variable is to make it easier to run commands on future logins. While we usually guide people to switch directory to `/opt/redash` first, not everyone follows every instruction :)

**Comment by rwsv3** [comment]
Understandable, and yes you're correct, I was reading through the lines, but after I had run the script. 
Thank you for the explanation
