### ISSUE TITLE
Missing directory in script run

### ISSUE THREAD

**Issue by roshankumar10** [getredash/setup#9]
Hi! Just wanted to point out an error I was able to work around.

I received the following error:
![image](https://user-images.githubusercontent.com/29102752/81237691-1a38bd00-8fb5-11ea-9a03-26bb83e2facc.png)

I was able to work around this by navigating to the opt directory and manually creating the redash directory before successfully running the script.

Thanks!

**Comment by ccwxl** [comment]
mac docker /opt/redash/env is also like this

**Comment by arikfr** [comment]
The directory is being created here:
https://github.com/getredash/setup/blob/cb47626b6823cbafac407b3e8991e97f53121f6e/setup.sh#L27

It would be easier to understand what's going on if you include the full script output.

**Comment by deej81** [comment]
I stumbled on this, not sure if something has changed in later versions of ubuntu (I'm on 22.04) but it didn't like the double square brackets in the if statements. Changing to a single square bracket allowed the script to run
![image](https://user-images.githubusercontent.com/7371682/178514007-95d47517-b4e5-4a57-93d0-9a5b5058db89.png)

**Comment by snickerjp** [comment]
I have corrected the problem with this pull request. #44
